### ISSUE TITLE
Can't get inline image from Gmail API

### ISSUE THREAD

**Issue by Lepelley** [zbateson/mail-mime-parser#111]
Hello,

`<?php
// ...
$mime = ZBateson\MailMimeParser\Message::from(Base64Url::decode($mail->getRaw()));
echo $mime->getHtmlContent();`

I'm getting the right mail, with HTML like i want, but images sources are replaced by : `cid:image.png`.
I understand that they put images in attachments, but can't get a way to make it work.

**Comment by zbateson** [comment]
Hi @Lepelley --

The cid URL scheme points to an attachment with the given Content-Id header.  You can read more about it here: https://tools.ietf.org/html/rfc2111

Although the actual "replacement" of the image with content is beyond the scope of a mail parser (you may want to inline it, serve it as a URL, display it in a window or you just want to look at the html content), you can find parts with a given Content-Id easily:

```php
$message = Message::from(...);
$part = $message->getPartByContentId('the content ID');
```
For an example, although I'm doing it a bit differently (I wanted to use the attachment's index to retrieve a part rather than the Content-Id), you can check out how I replaced it in here:

https://github.com/zbateson/mailbox-folder/blob/ef013a942811d1f4dafb7ae905afa812b9c905b7/src/App/Actions/EmailRestAction.php#L36

In that example it inserts a link to /emails/{id}/attachments/{att_id}/{filename}?inline=true, which causes this action:

https://github.com/zbateson/mailbox-folder/blob/master/src/App/Actions/EmailAttachmentAction.php

Hope that helps!

**Comment by Lepelley** [comment]
Helps a lot, thank you !

**Comment by didi1357** [comment]
Hey,

sorry for commenting on this old post. Maybe my info is already outdated, but I found this thread via google and it pointed me to finding this rather easy solution for the "problem beyond scope" of embedding cid scheme attached pictures in the HTML output:

```
  $content = $message->getHtmlContent();
  $domDocument = new DOMDocument();
  libxml_use_internal_errors(true); //mute warnings of non well formated $content
  $domContent = $domDocument->loadHTML($content);
  $images = $domDocument->getElementsByTagName('img');
  foreach ($images as $image)
  {
    //image links are parsed to find out whether they are embedded or external:
    $srcLink = $image->getAttribute('src');
    $components = parse_url($srcLink);
    if($components !== false)
    {
      if(strtolower($components['scheme'] == 'cid'))
      {
        //this is handling of embedded images as attachments
        $contentId = $components['path'];
        $part = $message->getPartByContentId($contentId);
        $imgContent = $part->getContent();
        $imgContentType = $part->getHeaderValue(HeaderConsts::CONTENT_TYPE);
        //convert attachment to direct embedded base64 data:
        $image->setAttribute('src', 'data:' . $imgContentType . ';base64,' . base64_encode($imgContent));
      }
      elseif(strtolower($components['scheme'] == 'data'))
      {
        //do nothing, this is handling of embedded images, e.g.:
        //<img src="data:image/jpg;base64,{{base64-data-string here}}" />
        //by leaving it as it is => will already be properly displayed!
      }
      else
      {
        //handling of external links beginning with e.g. http/https (in my case I wanted to remove them)
        $image->setAttribute('src', ''); //by removing image links
      }
    }
    else
    {
      //in case parsing of src url fails:
      $image->setAttribute('src', ''); //also remove image link
    }
  }
  echo $domDocument->saveHTML();
```

My solution basically just parses the HTML and replaces cid references with the data from the attachment. Am I missing some edge cases here, or is it really that easy? If so, wouldn't this be a feasible solution for your library as well, @zbateson ?

Best regards,
Didi

**Comment by zbateson** [comment]
Hi @didi1357 --

Thanks for that -- I'm sure people will find it helpful searching like you have :)

Beyond scope meaning I don't think it belong in the library.  It's certainly adjacent and very close, but not related to the actual parsing and reading of email content.  I could see it be desirable to an 'email client' that uses an email parser to read emails _and also displays_ the email to an end user, but there could be many 'very close' things (like maybe finding the 'reply' portion of an email, stripping out the rest) that aren't strictly 'parsing' and should be in separate libraries.

All the best and thanks again!
