### ISSUE TITLE
Zero byte attachments

### ISSUE THREAD

**Issue by WMGS** [zbateson/mail-mime-parser#118]
Hi,

I'm having issues with attachments. When the file is written to the server, the file size is always zero bytes. 
Tested with PDF and JPG files. Tried 50K file and 2MB file with same results.

I am using the sample found here: https://github.com/zbateson/mail-mime-parser/issues/15
Using PHP 7.0.33 on Linux webserver.

**Comment by zbateson** [comment]
Hi @WMGS --

That example is outdated: getContentResourceHandle has been deprecated.  That call should be replaced with getBinaryContentResourceHandle.  I added an updated example to the homepage of the website (that being the only change).

Having said that, that deprecation shouldn't be an issue either way for what you're experiencing.  It might just be an environment issue -- I recommend trying to echo the attachment... for example, instead of the stream_copy_to_stream line, do: ``` echo stream_get_contents($att->getBinaryContentResourceHandle()); ``` and see if that works.  It might just be an issue writing to the file on your server.

All the best

**Comment by zbateson** [comment]
Please reopen/add additional info if this is still an issue.
