### ISSUE TITLE
How to get all TO email addresses 

### ISSUE THREAD

**Issue by pagedesigner** [zbateson/mail-mime-parser#212]
hi, i've noticed that first email ID in TO header line is picked, if we have multiple email IDs it only picks first one:

`$message->getHeaderValue(HeaderConsts::TO);`

thanks

**Comment by zbateson** [comment]
Hi @pagedesigner --

That's by design.  You can get an IHeader object, in this case an AddressHeader, if you call ``` $message->getHeader ``` instead of getHeaderValue.

https://mail-mime-parser.org/api/2.2/classes/ZBateson-MailMimeParser-Message-IMimePart.html#method_getHeader
https://mail-mime-parser.org/api/2.2/classes/ZBateson-MailMimeParser-Header-AddressHeader.html

All the best
