### ISSUE TITLE
Support for newer versions of mb-wrapper and stream-decorators

### ISSUE THREAD

**Issue by phpfui** [zbateson/mail-mime-parser#234]
I noticed you now have newer version of stream-decorators and mb-wrapper that only support PHP 8.0 and higher!  Big YES here!

But mail-mime-parser is still requiring the older versions. Are the new versions compatible with the 2.4 version?  If so, do you want a PR to update the composer.json?

I was just doing a `composer outdated` and noticed this.

**Comment by zbateson** [comment]
Hi @phpfui 

I'm working on a v3 release that'll be updated soon to include them.  There's a small change I mostly finished working on to support them because they now throw an exception for unsupported charsets.  It's been a very busy period so progress has been slow, sorry to you and anyone waiting!  It's super close now :)

Because they throw exceptions and require php8, I will not be including them in 2.4.

Thanks again :)

**Comment by phpfui** [comment]
Awesome! Let me know if you need any help or testing.

**Comment by zbateson** [comment]
Oh wow, yes, testing would be amazing.  I'll do a beta release in a bit if you feel like playing around :)

**Comment by phpfui** [comment]
Yes, let me know.

**Comment by zbateson** [comment]
Well that was a bit longer than expected, sorry!

Finally got a beta out there.  I put some basic notes in [3.0.0-beta](https://github.com/zbateson/mail-mime-parser/releases/tag/3.0.0-beta) but honestly I don't know how helpful they are.

I still need to:

- write some more tests for HeaderParts
- add tests for some missing new HeaderPart classes and consumer classes

I'll add more to that list if something else comes up.

**Comment by phpfui** [comment]
I'll try this on a branch and see if I can set up a live server to test against.  Will let you know of any issues, but might not be till next week.
