### ISSUE TITLE
Composer issues / suggestions

### ISSUE THREAD

**Issue by lukasmedia** [zbateson/mail-mime-parser#68]
Composer issues / suggestions:

> Package herrera-io/json is abandoned, you should avoid using it. Use kherge/json instead.
> Package kherge/version is abandoned, you should avoid using it. No replacement was suggested.
> Package herrera-io/phar-update is abandoned, you should avoid using it. No replacement was suggested.

**Comment by zbateson** [comment]
Hi @lukasmedia 

Unfortunately those are upstream dependencies for packages MailMimeParser is using.  They aren't a huge concern though since they're only development dependencies.  If you install with ``` --no-dev ``` you won't see that message.

herrera-io/phar-update is a dependency of phpdocumentor/phpdocumentor, and both herrera-io/json and kherge/version are dependencies of herrera-io/phar-update.  phpdocumentor is used to generate api documentation for the wiki pages.

I will try updating phpdocumentor to its latest version and see if that's been resolved on their end (looks like it might be).  I'll keep this issue open till I get a chance to look into that.

Thank you

**Comment by zbateson** [comment]
phpdoc now not included as a dev dependency.
