### ISSUE TITLE
Provide easy parser of Received headers

### ISSUE THREAD

**Issue by tomsommer** [zbateson/mail-mime-parser#78]
It would be nice if there was a built in parser for the Received headers, like there is for Address and Date

**Comment by zbateson** [comment]
Looking further into this, parsing "Received" seems like a huge headache -- I was looking at the tests written for a python script and am baffled by the variety... just looking at the "from" part gives me a number of variations for where 'name', 'ip' and 'hostname' could show up: https://github.com/Te-k/pyreceived/blob/master/test.py

It would be much easier of course if I was only parsing the main parts, so the parsed header class provided a "from", a "by", an "id", etc... rather than "fromName", "fromIp", "fromHostname", but I guess it all depends on how this information is used.

Could you perhaps expand on your use-case and tell me what parts you're interested in?  I've noticed sometimes "cipher", "server", "envelope-from", "envelope-for", "protocol" are some example additional fields as well... how useful is all this given that it's all possibly missing, or could be tampered with or faked entirely?

**Comment by tomsommer** [comment]
My first use-case what to use it to verify TLS delivery through the Received chain. So "fromName", "fromIp" is not needed, that would in any case be over-the-top

**Comment by zbateson** [comment]
Even that's pretty difficult to determine as there are no standards to follow.  I'm inclining towards not accepting this as part of the library at this point, because:

* I'd be in a constant race to correctly parse headers from an infinite number of new possible servers or versions, always losing out at some point when a new "Received" header is discovered, or some random server somewhere decides to be clever
* The library in its current form tries to be standards-compliant rather than all-encompassing... I'd rather build confidence in that what the library claims to parse from a message is true considering 1) standards, and 2) common practice (e.g. commonly ignored parts of a standard or mistakes in implementation).

I think parsing the Received header belongs outside of this library for that reason -- a library that is specifically designed to be constantly chasing new Received header formats discovered, not one looking for reliability.

I'd be happy to consider doing that with some help if anyone's interested in a joint effort.

**Comment by tomsommer** [comment]
That makes sense, I'm however puzzled there is no RFC in regards to `Received:`
`Received: From X by Y [with Z]; DATE` seems to be as close as one can get

**Comment by zbateson** [comment]
I found it defined here: https://tools.ietf.org/html/rfc5321#section-4.4
It gives some defined structure but it's pretty loose as far as values go.  I could consider providing the basic parts: From, By, Via, With, For, ID and Timestamp if that helps... for any field that exists, provide a string for its value?
I haven't seen an example use of Via though looking at the pyreceived tests.

**Comment by tomsommer** [comment]
That would be a helpful start

**Comment by zbateson** [comment]
Happy to add that, but I'm not sure you'll particularly love it.

When/if servers add TLS connection info, it's usually in a comment... so you'd have to look through parsed comments (I'll clarify with an example when I've uploaded some code).  Figuring out if a message was transmitted via TLS from point-to-point is just not possible looking at a Received header for many reasons.

Having said that, I can at least parse the standardized parts -- maybe parts of it are useful for other use cases.

**Comment by tomsommer** [comment]
I realise that, but it would still be helpful :)

**Comment by zbateson** [comment]
I've pushed some commits to master.  You should be able to:

- $message->getAllHeadersByName('Received') and get an array of ReceivedHeader objects
- call $header->getFromName, getFromHostname, getFromAddress (and getByName, etc...)
- call $header->getValueFor('with') (or 'via', 'id', 'for', 'from' or 'by' -- 'from' and 'by' would return full value of the header, e.g. 'name (host.tld [1.2.3.4])'
- call $header->getDateTime() to get a DateTime for the date/time stamp in the header.

Please have a look and let me know what you think.  I'll probably release a 1.1 for it and a few other changes over the weekend if all is well.

**Comment by tomsommer** [comment]
Excellent job :)

**Comment by zbateson** [comment]
Released in 1.1 :)

**Comment by zbateson** [comment]
Closing this as it seems resolved and no further comments, if you find any issues please open a separate ticket.
