### ISSUE TITLE
mail-mime-parser vs php-mime-mail-parser

### ISSUE THREAD

**Issue by eXorus** [zbateson/mail-mime-parser#87]
Hello @zbateson,

I have analyzed your package and **you did a very great job to parse an email without mailparse**. I'm the main contributor of https://github.com/php-mime-mail-parser/php-mime-mail-parser that you should know and I plan to create a new library from scratch: more modern than today. :muscle:

Currently I have compared only 26 test emails from my repository and I found 2 issues:

**Error 1 (subject)**
https://gitlab.com/mailcare/parser/blob/master/tests/emails/m0022
Actual subject: `[PRJ-OTH] asdf árvíztűrő tükörfúrógép`
Expected subject: `[PRJ-OTH] asdf  árvíztűrő tükörfúrógép` (2 spaces between asdf and árvíztűrő)

**Error 2 (attachment)**
https://gitlab.com/mailcare/parser/blob/master/tests/emails/m0024
Actual attachment: .doc 24,6ko [Biodiversité de semaine en semaine.pdf](https://github.com/zbateson/mail-mime-parser/files/2976484/Biodiversite.de.semaine.en.semaine.pdf)
Expected attachment: .doc 27,6ko [Biodiversité de semaine en semaine.pdf](https://github.com/zbateson/mail-mime-parser/files/2976480/Biodiversite.de.semaine.en.semaine.pdf)

:question: **Question (get all attachments)**
Your function `getAllAttachmentParts` doesn't return all the attachments:
- inline attachments
- calendar attachments

I know it's difficult to choose what is an attachment and I would like your point of view.

:rocket: **Performance**
Of course the performance of this library is under php-mime-mail-parser. PHP can not win against C.
mail-mime-parser: 203.77 ms 16,22 MB
php-mime-mail-parser: 105 ms 12,44 MB (faster and less memory usage)

**Conclusion**
For more information I created 3 new repositories:
https://gitlab.com/mailcare/parser to handle all the tests and the interface to switch between mailparse or pure php
https://gitlab.com/mailcare/parser-php adapter for your repository
https://gitlab.com/mailcare/parser-mailparse adapter for my repository

I would like to continue to create mailcare/parser to have a clean interface for parsing email (I don't know if you are interesting to work with me) and give to the user the power to switch between different implementation. And also to share between us a set of test emails and maybe some decoding part.

Once again congratulations for your work I was not expecting this level of quality. :clap:

**Comment by zbateson** [comment]
Hi @eXorus,

I must say that's quite the praise, thank you for the recognition :blush: of course I know your project and have been following your work.

> Error 1 (subject)
https://gitlab.com/mailcare/parser/blob/master/tests/emails/m0022
Actual subject: [PRJ-OTH] asdf árvíztűrő tükörfúrógép
Expected subject: [PRJ-OTH] asdf árvíztűrő tükörfúrógép (2 spaces between asdf and árvíztűrő)

This one's not so clear to me that the second space needs to be there.  I don't think the specification specifically says, instead it just says:

> Ordinary ASCII text and 'encoded-word's may appear together in the
    same header field.  However, an 'encoded-word' that appears in a
    header field defined as '*text' MUST be separated from any adjacent
    'encoded-word' or 'text' by 'linear-white-space'.

It specifically specifies elsewhere that white space between two encoded parts should be ignored though, so:

```
Subject: =?UTF-8?Q?bl?=      =?UTF-8?Q?ah?=
```

Should be interpreted as "blah".  I don't think you're wrong, I just don't think it specifically says either way.  It has been a while since I've gone over all of this though, so feel free to correct me and point it out to me :)

> Error 2 (attachment)
https://gitlab.com/mailcare/parser/blob/master/tests/emails/m0024
Actual attachment: .doc 24,6ko Biodiversité de semaine en semaine.pdf
Expected attachment: .doc 27,6ko Biodiversité de semaine en semaine.pdf

I think this may be related to using php stream objects versus Psr7 streams directly but I'm not sure.  Someone had reported something similar earlier in #84 which I'd been waiting to hear about.  Another user reported something similar privately and it was fixed by using ``` $message->getContentStream() ``` instead of ``` $message->getContentResourceHandle() ```.  I wasn't able to determine what the issue was at the time without a working test case, so thank you... I'll have a closer look :)

> question Question (get all attachments)
Your function getAllAttachmentParts doesn't return all the attachments:
>
>    inline attachments
    calendar attachments
>
> I know it's difficult to choose what is an attachment and I would like your point of view.

Yes, this was one I struggled with too.  I see my documentation on that isn't very good as well unfortunately.

I think I originally mixed what I considered an attachment vs what I didn't.  Originally, anything that specified a disposition I considered an "attachment"... anything without a disposition I considered part of the email.  This became a problem when I realized some emails may specifically define their main message parts as "inline" (see #34).

I then shifted.  If an email specifically tells me a part is an attachment, I consider it an attachment.  Otherwise it's inline and should be part of the message.  I don't have a great way of retrieving "all inline parts of a message" besides using ``` $message->getAllParts(PartFilter::fromDisposition('inline')); ``` which isn't too obvious or user friendly.

>  Performance
Of course the performance of this library is under php-mime-mail-parser. PHP can not win against C.
mail-mime-parser: 203.77 ms 16,22 MB
php-mime-mail-parser: 105 ms 12,44 MB (faster and less memory usage)

Of course :) the longer the test, the larger the emails, the farther those numbers would be.

I like your plan and am on-board.  I think most of this discussion should probably happen on your end though in one of your new projects.  I particularly like your idea of having some shared tests, and would be happy to help with moving header decoding to a shared library or something if that makes sense.

**Comment by eXorus** [comment]
**Error 1:**
I agree with you for the interpretation, both side can be truth.

**Error 2:**
Nice to help you, I hope I would be able to integrate also your tests in my library to check the inverse.

**Question:**
With my brother 2 weeks ago I struggled to define the interface for getAttachments:
- getAllAttachments => return all except the text and html part
- getRealAttachments => return only attachments not inline
- getInlineAttachments => return inline attachments
....

I'm glad to read your nice reply. Let's continue to talk on mailcare I don't want to pollute your repository.
You can close this issue or keep it to fix the attachment issue.

**Comment by zbateson** [comment]
Issue with the attachment fixed with latest zbateson/stream-decorators included in 1.1.4, thanks again :+1:
